# Generated by Django 2.2.28 on 2025-06-08 00:46

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0012_userprofile_language'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='session_keys',
            field=jsonfield.fields.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='acm_problems_status',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='oi_problems_status',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
