# Generated by Django 4.2.23 on 2025-06-18 21:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0014_userstreak_dailycheckin"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserPracticeProfile",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skill_level", models.FloatField(default=0.5)),
                ("strongest_tags", jsonfield.fields.JSONField(default=list)),
                ("weakest_tags", jsonfield.fields.JSONField(default=list)),
                ("avg_difficulty_solved", models.FloatField(default=0)),
                ("last_analyzed", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="practice_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "user_practice_profile",
            },
        ),
        migrations.CreateModel(
            name="ProblemRecommendation",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("problem_id", models.IntegerField()),
                ("match_score", models.FloatField()),
                ("ai_reason", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("clicked", models.BooleanField(default=False)),
                ("solved", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="problem_recommendations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "problem_recommendation",
                "ordering": ["-created_at", "-match_score"],
            },
        ),
    ]
