# Generated by Django 4.2.23 on 2025-06-19 00:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0015_userpracticeprofile_problemrecommendation"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="problemrecommendation",
            unique_together={("user", "problem_id")},
        ),
    ]
