# Generated by Django 4.2.23 on 2025-06-21 22:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0016_alter_problemrecommendation_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="mood_clear_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="mood_emoji",
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="status",
            field=models.CharField(
                choices=[
                    ("practicing", "Practicing"),
                    ("learning", "Learning"),
                    ("competing", "In Contest"),
                    ("debugging", "Debugging"),
                    ("reviewing", "Reviewing"),
                    ("resting", "Taking Break"),
                ],
                default="practicing",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="status_color",
            field=models.CharField(default="#52c41a", max_length=7),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="status_message",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
