# Generated by Django 4.2.23 on 2025-06-28 02:44

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0017_userprofile_mood_clear_at_userprofile_mood_emoji_and_more"),
        ("account", "add_student_group"),
    ]

    operations = []
