# Generated by Django 4.2.23 on 2025-07-05 19:09

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import jsonfield.fields


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0018_merge_20250628_0244"),
    ]

    operations = [
        migrations.AddField(
            model_name="userstreak",
            name="check_in_days",
            field=jsonfield.fields.JSONField(default=list),
        ),
        migrations.AddField(
            model_name="userstreak",
            name="total_problems_solved",
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name="ProblemSuggestion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("problem_id", models.IntegerField()),
                ("ai_reason", models.TextField()),
                ("match_score", models.FloatField(default=0.0)),
                ("suggested_time", models.DateTimeField(auto_now_add=True)),
                ("is_viewed", models.BooleanField(default=False)),
                ("is_attempted", models.BooleanField(default=False)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "problem_suggestion",
                "indexes": [
                    models.Index(
                        fields=["user", "-match_score"],
                        name="problem_sug_user_id_e5231a_idx",
                    ),
                    models.Index(
                        fields=["user", "-suggested_time"],
                        name="problem_sug_user_id_3ba17d_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DailyProblemSuggestion",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("problem_id", models.IntegerField()),
                ("suggested_date", models.DateField(default=datetime.date.today)),
                ("ai_reason", models.TextField()),
                ("is_completed", models.BooleanField(default=False)),
                ("completed_time", models.DateTimeField(blank=True, null=True)),
                ("create_time", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "daily_problem_suggestion",
                "indexes": [
                    models.Index(
                        fields=["user", "suggested_date"],
                        name="daily_probl_user_id_6f3ecd_idx",
                    )
                ],
                "unique_together": {("user", "suggested_date")},
            },
        ),
    ]
