# Generated by Django 2.2.28 on 2025-06-08 00:46

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('options', '0003_migrate_languages_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysoptions',
            name='value',
            field=jsonfield.fields.JSONField(),
        ),
    ]
