# Generated by Django 2.2.28 on 2025-06-08 00:46

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('contest', '0010_auto_20190326_0201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acmcontestrank',
            name='submission_info',
            field=jsonfield.fields.JSONField(default=dict),
        ),
        migrations.AlterField(
            model_name='contest',
            name='allowed_ip_ranges',
            field=jsonfield.fields.JSONField(default=list),
        ),
        migrations.AlterField(
            model_name='oicontestrank',
            name='submission_info',
            field=jsonfield.fields.JSONField(default=dict),
        ),
    ]
