# Generated by Django 4.2.23 on 2025-06-29 02:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("homework", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="homeworkassignment",
            name="auto_grade",
            field=models.BooleanField(default=True),
        ),
    ]
